#! /bin/bash
#
# Compile and link the main program
#

# Compile the main program
c++ -Wall -Wextra -pedantic -Werror -std=c++11 -I${PACKAGE1_INC} -c t2.cc

# Link the main program against the package1 library and the system libraries.
c++ -o t2 t2.o ${PACKAGE1_LIB}/libpackage1.a
