#! /bin/bash
#
# Compile and link the main program
#

# Determine the correct suffix to give to the dynamic library.
if [[ "$OSTYPE" == darwin* ]]; then
  SUFFIX=dylib
elif [[ "$OSTYPE" == linux* ]]; then
  SUFFIX=so
else
  echo "Unable to identify operating system"
  exit 1
fi

# Compile the function.
c++ -Wall -Wextra -pedantic -Werror -std=c++11 -c times2.cc

# Link the object file into a dynamic library.
c++ -o libpackage1.${SUFFIX} -shared times2.o

# Compile and link the main program against the package1 library and
# the system libraries.
c++ -o t1 t1.cc -L. -lpackage1
